---
# site.yml – main orchestrator playbook

- name: Setup git config & Github SSH
  import_playbook: playbook.ssh.yml

- name: Clone dotfiles and passowrd repos
  import_playbook: playbook.clone.yml

- name: Setup gnupg keys
  import_playbook: playbook.gpg.yml
